modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"
issueTrackerURL = "${mod_issues}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${mod_source}"
logoFile = "assets/hydrogen/icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "hydrogen.mixins.json"

[[mixins]]
config = "hydrogen.client.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dep_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${forge_mc_range}"
ordering = "NONE"
side = "BOTH"
